### ISSUE TITLE
Alle Now Addons Probleme auf Android

### ISSUE THREAD

**Issue by papandy** [bromix/plugin.video.rtl2-now.de#6]
Hallo,
habe leider bei allen Now Addons sowie bei TLC Addon das Problem das wenn ich das jeweilige Addon starten möchte nur die "Arbeitet..." Meldung bekomme und dann war verbleibt Kodi dabei. Mit der Back-Taste kann ich zwar dann in Kodi weiter navigieren aber kein anderes Addon mehr starten da das Now/TLC Addon noch im Hintergrund zu hängen scheint.
Ich habe dieses Problem aber nur auf meiner DYON Andromeda Android Tv Box mit Kodi 14.1, nicht auf meinem Windows Laptop mit Kodi 14.2.

**Comment by bromix** [comment]
Das ist leider auch schon die Ursache des Problems. Da kann ich leider nichts machen. Bitte an den Entwickler wenden, von dem die KODI Version kommt.
